/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MakeRoomImport } from './routes/make-room'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as RoomIndexImport } from './routes/room/index'
import { Route as RoomRoomIDImport } from './routes/room/$roomID'
import { Route as RoomRoomIDIndexImport } from './routes/room/$roomID/index'
import { Route as RoomRoomIDStageImport } from './routes/room/$roomID/stage'
import { Route as RoomRoomIDPlayImport } from './routes/room/$roomID/play'

// Create/Update Routes

const MakeRoomRoute = MakeRoomImport.update({
  id: '/make-room',
  path: '/make-room',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomIndexRoute = RoomIndexImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomIDRoute = RoomRoomIDImport.update({
  id: '/room/$roomID',
  path: '/room/$roomID',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomIDIndexRoute = RoomRoomIDIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomRoomIDRoute,
} as any)

const RoomRoomIDStageRoute = RoomRoomIDStageImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => RoomRoomIDRoute,
} as any)

const RoomRoomIDPlayRoute = RoomRoomIDPlayImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => RoomRoomIDRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/make-room': {
      id: '/make-room'
      path: '/make-room'
      fullPath: '/make-room'
      preLoaderRoute: typeof MakeRoomImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomID': {
      id: '/room/$roomID'
      path: '/room/$roomID'
      fullPath: '/room/$roomID'
      preLoaderRoute: typeof RoomRoomIDImport
      parentRoute: typeof rootRoute
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomID/play': {
      id: '/room/$roomID/play'
      path: '/play'
      fullPath: '/room/$roomID/play'
      preLoaderRoute: typeof RoomRoomIDPlayImport
      parentRoute: typeof RoomRoomIDImport
    }
    '/room/$roomID/stage': {
      id: '/room/$roomID/stage'
      path: '/stage'
      fullPath: '/room/$roomID/stage'
      preLoaderRoute: typeof RoomRoomIDStageImport
      parentRoute: typeof RoomRoomIDImport
    }
    '/room/$roomID/': {
      id: '/room/$roomID/'
      path: '/'
      fullPath: '/room/$roomID/'
      preLoaderRoute: typeof RoomRoomIDIndexImport
      parentRoute: typeof RoomRoomIDImport
    }
  }
}

// Create and export the route tree

interface RoomRoomIDRouteChildren {
  RoomRoomIDPlayRoute: typeof RoomRoomIDPlayRoute
  RoomRoomIDStageRoute: typeof RoomRoomIDStageRoute
  RoomRoomIDIndexRoute: typeof RoomRoomIDIndexRoute
}

const RoomRoomIDRouteChildren: RoomRoomIDRouteChildren = {
  RoomRoomIDPlayRoute: RoomRoomIDPlayRoute,
  RoomRoomIDStageRoute: RoomRoomIDStageRoute,
  RoomRoomIDIndexRoute: RoomRoomIDIndexRoute,
}

const RoomRoomIDRouteWithChildren = RoomRoomIDRoute._addFileChildren(
  RoomRoomIDRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/make-room': typeof MakeRoomRoute
  '/room/$roomID': typeof RoomRoomIDRouteWithChildren
  '/room': typeof RoomIndexRoute
  '/room/$roomID/play': typeof RoomRoomIDPlayRoute
  '/room/$roomID/stage': typeof RoomRoomIDStageRoute
  '/room/$roomID/': typeof RoomRoomIDIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/make-room': typeof MakeRoomRoute
  '/room': typeof RoomIndexRoute
  '/room/$roomID/play': typeof RoomRoomIDPlayRoute
  '/room/$roomID/stage': typeof RoomRoomIDStageRoute
  '/room/$roomID': typeof RoomRoomIDIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/make-room': typeof MakeRoomRoute
  '/room/$roomID': typeof RoomRoomIDRouteWithChildren
  '/room/': typeof RoomIndexRoute
  '/room/$roomID/play': typeof RoomRoomIDPlayRoute
  '/room/$roomID/stage': typeof RoomRoomIDStageRoute
  '/room/$roomID/': typeof RoomRoomIDIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/make-room'
    | '/room/$roomID'
    | '/room'
    | '/room/$roomID/play'
    | '/room/$roomID/stage'
    | '/room/$roomID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/make-room'
    | '/room'
    | '/room/$roomID/play'
    | '/room/$roomID/stage'
    | '/room/$roomID'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/make-room'
    | '/room/$roomID'
    | '/room/'
    | '/room/$roomID/play'
    | '/room/$roomID/stage'
    | '/room/$roomID/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MakeRoomRoute: typeof MakeRoomRoute
  RoomRoomIDRoute: typeof RoomRoomIDRouteWithChildren
  RoomIndexRoute: typeof RoomIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MakeRoomRoute: MakeRoomRoute,
  RoomRoomIDRoute: RoomRoomIDRouteWithChildren,
  RoomIndexRoute: RoomIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/make-room",
        "/room/$roomID",
        "/room/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/make-room": {
      "filePath": "make-room.tsx"
    },
    "/room/$roomID": {
      "filePath": "room/$roomID.tsx",
      "children": [
        "/room/$roomID/play",
        "/room/$roomID/stage",
        "/room/$roomID/"
      ]
    },
    "/room/": {
      "filePath": "room/index.tsx"
    },
    "/room/$roomID/play": {
      "filePath": "room/$roomID/play.tsx",
      "parent": "/room/$roomID"
    },
    "/room/$roomID/stage": {
      "filePath": "room/$roomID/stage.tsx",
      "parent": "/room/$roomID"
    },
    "/room/$roomID/": {
      "filePath": "room/$roomID/index.tsx",
      "parent": "/room/$roomID"
    }
  }
}
ROUTE_MANIFEST_END */
